// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Condition is an autogenerated mock type for the Condition type
type Condition struct {
	mock.Mock
}

type Condition_Expecter struct {
	mock *mock.Mock
}

func (_m *Condition) EXPECT() *Condition_Expecter {
	return &Condition_Expecter{mock: &_m.Mock}
}

// Field provides a mock function with given fields:
func (_m *Condition) Field() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Field")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Condition_Field_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Field'
type Condition_Field_Call struct {
	*mock.Call
}

// Field is a helper method to define mock.On call
func (_e *Condition_Expecter) Field() *Condition_Field_Call {
	return &Condition_Field_Call{Call: _e.mock.On("Field")}
}

func (_c *Condition_Field_Call) Run(run func()) *Condition_Field_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Condition_Field_Call) Return(_a0 string) *Condition_Field_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Condition_Field_Call) RunAndReturn(run func() string) *Condition_Field_Call {
	_c.Call.Return(run)
	return _c
}

// Valueless provides a mock function with given fields:
func (_m *Condition) Valueless() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valueless")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Condition_Valueless_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valueless'
type Condition_Valueless_Call struct {
	*mock.Call
}

// Valueless is a helper method to define mock.On call
func (_e *Condition_Expecter) Valueless() *Condition_Valueless_Call {
	return &Condition_Valueless_Call{Call: _e.mock.On("Valueless")}
}

func (_c *Condition_Valueless_Call) Run(run func()) *Condition_Valueless_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Condition_Valueless_Call) Return(_a0 bool) *Condition_Valueless_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Condition_Valueless_Call) RunAndReturn(run func() bool) *Condition_Valueless_Call {
	_c.Call.Return(run)
	return _c
}

// isCondition provides a mock function with given fields:
func (_m *Condition) isCondition() {
	_m.Called()
}

// Condition_isCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isCondition'
type Condition_isCondition_Call struct {
	*mock.Call
}

// isCondition is a helper method to define mock.On call
func (_e *Condition_Expecter) isCondition() *Condition_isCondition_Call {
	return &Condition_isCondition_Call{Call: _e.mock.On("isCondition")}
}

func (_c *Condition_isCondition_Call) Run(run func()) *Condition_isCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Condition_isCondition_Call) Return() *Condition_isCondition_Call {
	_c.Call.Return()
	return _c
}

func (_c *Condition_isCondition_Call) RunAndReturn(run func()) *Condition_isCondition_Call {
	_c.Call.Return(run)
	return _c
}

// NewCondition creates a new instance of Condition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCondition(t interface {
	mock.TestingT
	Cleanup(func())
}) *Condition {
	mock := &Condition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
