// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// numbers is an autogenerated mock type for the numbers type
type numbers struct {
	mock.Mock
}

type numbers_Expecter struct {
	mock *mock.Mock
}

func (_m *numbers) EXPECT() *numbers_Expecter {
	return &numbers_Expecter{mock: &_m.Mock}
}

// newNumbers creates a new instance of numbers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newNumbers(t interface {
	mock.TestingT
	Cleanup(func())
}) *numbers {
	mock := &numbers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
